const mongosse = require('mongoose')

const Order =  mongosse.Schema({
    product_id:{
        type:String,
        require:true
    },
    order_id:{
        type:String,
        require:true
    },
    seller_id:{
        type:String,
        require:true
    },

    buyer_id:{
        type:String,
        require:true
    },
    buyer_first_name:{
        type:String,
        require:true,
    },
    buyer_last_name:{
        type:String,
        require:true,
    },
    buyer_phone:{
        type:String,
        require:true,
    },
    buyer_address:{
        type:String,
        require:true,
    },
    buyer_email:{
        type:String,
        require:true,
    },
    buyer_city:{
        type:String,
        require:true,
    },
    buyer_state:{
        type:String,
        require:true,
    },
    buyer_country:{
        type:String,
        require:true,
    },
    quantity:{
        type:Number,
        default:1,
        require:true
    },
    shipping_duration:{
        type:String,
        require:true,
    },
    shipping_method:{
        type:String,
        require:true,
    },
    shipping_cost:{
        type:Number,
        require:true
    },

    total_price:{
        type:Number,
        require:true
    },
    payment_method:{
        type:String,
        require:true
    },
    payment_status:{
        type:String,
        require:true
    },
    payment_reference:{
        type:String,
        require:true
    },
    authorization_url:{
        type:String,
        require:true
    },
    access_code:{
        type:String,
        require:true
    },
    order_status:{
        type:String,
        require:true,
        default:"pending"
    },
    date_placed:{
        type:Date,
        default:Date.now
    },
    date_delivered:{
        type:Date,
        require:null
    },
    cart_id:{
        type:String,
        require:true
    },
    tracking_number:{
        type:String,
        require:true
    },
    items:{
        type:Array,
        default:[],
        required:true
    },
    history:{
        type:Array,
        default:[],
        required:true,
    },
    comment:{
        type:Array,
        default:[],
        required:true,
    }
})

module.exports = mongosse.model('tkk_orders', Order)