export const REGISTER_NEW_USER = "REGISTER-NEW-USER"
export const SET_ALERT = "SET-ALERT"
export const REMOVE_ALERT = "REMOVE-ALERT"
export const SET_TYPE = "SET-TYPE"
export const USER_LOADED = "USER-LOADED"
export const LOAD_USER_ERROR = "LOAD-USER-ERROR"
