const mongoose = require('mongoose');
const JobListing = mongoose.Schema({
    jobSellerId:{
        type:String,
        require:true
    },
    jobCategory:{
        type:String,
        require:true
    },
    jobSubCategory:{
        type:String,
        require:true
    },
    jobImage:{
        type:Array,
        require:true
    },
    jobRegion:{
        type:String,
        require:true
    },
    jobTitle:{
        type:String,
        require:true
    },
    jobDescription:{
        type:String,
        require:true
    },
    jobBusinessIndustry:{
        type:String,
        require:true
    },
    jobType:{
        type:String,
        require:true
    },
    jobBusinessFunction:{
        type:String,
        require:true
    },
    jobRole:{
        type:String,
        require:true
    },
    jobMinQualification:{
        type:String,
        require:true
    },
    jobYearsOfExp:{
        type:String,
        require:true
    },
    jobEduSpecialization:{
        type:String,
        require:true
    },
    jobSkills:{
        type:String,
        require:true
    },
    jobMaxAge:{
        type:String,
        require:true
    },
    jobGenderPref:{
        type:String,
        require:true
    },
    jobSalary:{
        type:String,
        require:true
    },
    jobApplicationDeadline:{
        type:String,
        require:true
    },
    jobAdvanceListing:{
        type:String,
        require:true
    },
    jobCreatedOn:{
        type:Date,
        default: Date.now
    }
})

module.exports = mongoose.model('tkk_jobslisting', JobListing)